export const DEFAULT_HISTORY_DAYS = 90;
export const DEFAULT_SHORTAGE_THRESHOLD_DAYS = 10;
export const DEFAULT_OVERSTOCK_THRESHOLD_DAYS = 90;
export const DEFAULT_MILD_OVERSTOCK_THRESHOLD_DAYS = 60;
export const MAX_COVERAGE_DAYS = 365;
export const MIN_DAILY_SALES = 0.1;
export const MIN_SALES_FOR_FORECAST = 10;
export const MIN_RECOMMENDED_QTY = 5;
export const DEFAULT_LEAD_TIME_DAYS = 14;
export const DEFAULT_SAFETY_DAYS = 7;
export const CACHE_MAX_MINUTES = 30;
export const DEFAULT_TARGET_COVERAGE = Math.max(
  DEFAULT_LEAD_TIME_DAYS + DEFAULT_SAFETY_DAYS,
  30,
);
export const DEFAULT_DIGEST_SEND_HOUR = 9;
export const DEFAULT_DIGEST_DAILY_ENABLED = false;
export const DEFAULT_DIGEST_WEEKLY_ENABLED = true;
